name: Release

on: 
  push:
    branches:
     - main
     - mirror
  
jobs:
  Release:
    env:
      SOURCE_PATH: Assets/Mirage.Profiler
      TARGET_PATH: Assets/Mirage.Profiler
    runs-on: windows-latest
    # needs: Tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.100'
  
      - name: Install unity-packer
        run: dotnet tool install -g unity-packer
  
      - name: Package

        run: >-
          unity-packer pack Mirage.Profiler.unitypackage 
          ${{ env.SOURCE_PATH }} ${{ env.TARGET_PATH }}
          LICENSE ${{ env.TARGET_PATH }}/LICENSE 
          README.md ${{ env.TARGET_PATH }}/README.md
          
      - uses: actions/upload-artifact@v1
        with:
          name: Mirage.Profiler.unitypackage
          path: Mirage.Profiler.unitypackage

      - name: Branch name
        run: echo ${GITHUB_REF}
    
      - name: Release
        uses: cycjimmy/semantic-release-action@v2
        with: 
          extra_plugins: |
            @semantic-release/exec
            @semantic-release/changelog
            @semantic-release/git
          branch: ${GITHUB_REF}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}